language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install poetry
  - poetry install -v
# command to run tests
script: pytest -vv -s
