language: python
python:
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install poetry
  - poetry install -v
# command to run tests
script: pytest -vv -s
